# Generated by Django 5.0.3 on 2024-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel_name',
            field=models.CharField(default='Стандартное название отеля', max_length=100),
            preserve_default=False,
        ),
    ]
