# Generated by Django 5.0.3 on 2024-05-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_booking_guest_booking_user_id_delete_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_services',
        ),
    ]
